server:
  port: 8888

spring:
  profiles:
    active: db
  jackson:
    # 该配置是用于解决jackson对于时间格式的配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: #密码
    database: 0 #指定数据库 默认0
    ssl: false  #是否使用ssl连接， 默认false
    timeout: 2000 # 连接超时时间， 单位毫秒 默认0
    pool:
      max-active: 8 #最大活跃连接数 默认8
      max-idle: 8   #最大空闲连接数 默认8
      max-wait: -1 # 获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。 默认值可能会因为获取不到连接， 导致事务无法提交，数据库被锁，大量线程处于等待状态的情况
      min-idle: 0 # 最小空闲连接数， 默认0
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # kafka 的认证机制
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='admin' password='admin';

logging:
  #  此配置是用于打印log日志所使用
  config: classpath:logback-spring.xml
  #  此配置是用与打印sql请求日志的
  level:
    demo: debug